version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dawn-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dawn}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dawn}
      POSTGRES_DB: ${POSTGRES_DB:-dawn}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./lib/db/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dawn"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: dawn-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  minio_data:
    driver: local
